### ISSUE TITLE
Worng version, even if it is the same version

### ISSUE THREAD

**Issue by TheMacraft878** [getItemFromBlock/Create-Tweaked-Controllers#18] opened 2024-05-07 16:35 UTC
I want to play Create 5 with someone on a server, but I get a message, that the version is not the same, even after checking it is the same and also getting the .jar from the server side as a copy, still the same error. The tergetet file is Kube JS.
It says the same version name, but something must be different, even though, the file is litterally the same.

**Comment by TheMacraft878** [comment] 2024-05-07 16:41
After the version on the server side changed, the Problem shifted to another mod, but this time with different versions.

**Comment by TheMacraft878** [comment] 2024-05-07 16:48
After fixing SkyGUIs, Kube Js is the problem again.

**Comment by getItemFromBlock** [comment] 2024-05-07 16:57
I don't understand, first of all what version of Create are you using ? (the exact version, like 0.5.1.f)
Then what version of Minecraft and of my mod (Create Tweaked Controllers) are you using ?
And finally send a screenshot of the error message, that I guess is appearing inside Minecraft when you connect to the server

**Comment by getItemFromBlock** [comment] 2024-05-07 16:58
Also what tells you that this is an error caused by my mod, and not by KubeJS ?

**Comment by TheMacraft878** [comment] 2024-05-09 17:36
Modpack version: 1.3.1
Minecraft Version: 1.20.1 using Forge
I would like to add, that I got to this link from the help menu of the Create Modpack, so I thought this is for the modpack. I'm sorry, if this is not the case. A screenshot is attached.
![Screenshot (46)](https://github.com/getItemFromBlock/Create-Tweaked-Controllers/assets/169183565/10cd1560-9c3c-488e-ba3b-05a19d1feb6c)

**Comment by getItemFromBlock** [comment] 2024-05-10 12:21
OK so the issue is related to KubeJS, but not with my mod as far as I can see
This repository is for the mod Create Tweaked Controllers
You should report this issue on their official repository instead: https://github.com/KubeJS-Mods/KubeJS/issues
Make sure to first search for similar issues, it might already have been reported

**Comment by TheMacraft878** [comment] 2024-05-10 18:32
Okay, thanks for the advice!

**Comment by getItemFromBlock** [comment] 2024-05-10 19:45
Alright, I will close this as there isn't much more I an do, but you can still comment here or create a new issue if you stumble upon a problem with my mod
Good luck with your KubeJS issue

**Closed as completed by getItemFromBlock** 2024-05-10 19:45 UTC
