### ISSUE TITLE
Resetting Mouse Sensitivity

### ISSUE THREAD

**Issue by DomezTheDragon** [getItemFromBlock/Create-Tweaked-Controllers#9] opened 2024-02-07 00:53 UTC
Resets my mouse sensitivity to default when i get off the controller (1.18.2)

**Comment by getItemFromBlock** [comment] 2024-02-07 07:34
The mod is supposed to set the mouse sensitivity to what was set before, are you using another mod(s) that could affect the mouse cursor sensitivity ?

**Comment by getItemFromBlock** [comment] 2024-02-11 15:27
I can't help you if you don't give more infos like what other mods are you using, or what are the reproduction steps.

**Comment by getItemFromBlock** [comment] 2024-02-15 01:56
Until new infos from your side, I will consider this a duplicate of https://github.com/getItemFromBlock/Create-Tweaked-Controllers/issues/11

**Comment by getItemFromBlock** [comment] 2024-03-24 00:19
Update is out for 1.19 and 1.20

**Closed as completed by getItemFromBlock** 2024-03-24 00:19 UTC
Labels: duplicate
