### ISSUE TITLE
only 6 buttons can be pressed at the same time

### ISSUE THREAD

**Issue by Rudyk-Artem** [getItemFromBlock/Create-Tweaked-Controllers#14] opened 2024-04-27 09:45 UTC
There is a problem: it is impossible to press more than 6 buttons at the same time. Most likely, this is related to the length of the array that stores what is currently activated. The length of this array is 6 elements as buttons on linked
controller and possibly increasing this length to 25 (the number of buttons on your controller) the problem will disappear.

P.S. translated by Google translator

**Comment by getItemFromBlock** [comment] 2024-04-27 16:52
This part of the code does not use an array (in opposition to create's linked controller implementation, which does uses an array). Instead, I use a 16 bit bitmask to send the state of all buttons, and another 32 bit variable to store the analog axis values. Here is the relevant code: [ControllerRedstoneOutput](https://github.com/getItemFromBlock/Create-Tweaked-Controllers/blob/dev-1.18/src/main/java/com/getitemfromblock/create_tweaked_controllers/controller/ControllerRedstoneOutput.java#L22)
I tested in a world just in case, I can press simultaneously all buttons of the controller without any issues.

What are you using as input source, a keyboard/mouse or a gamepad ?
If you are using a keyboard, then I think the issue is that your keyboard can't register more that 6 keys being pressed at the same time. In this case there is nothing that I can do since its a hardware issue.
You can check this using the following website : https://www.mechanical-keyboard.org/key-rollover-test/

**Comment by getItemFromBlock** [comment] 2024-05-05 00:20
Is there anything new about your problem ?

**Comment by getItemFromBlock** [comment] 2024-05-12 13:39
Closing this for now, let me know when you have anything new on this and I will reopen it

**Closed as not planned by getItemFromBlock** 2024-05-12 13:39 UTC

**Comment by Rudyk-Artem** [comment] 2026-05-02 22:20
Thanks for the explanation and sorry for not answering the question. I used a keyboard to bind the keys Y, A, X, B, Up, Down, Left, Right, Left Shoulder, Right Shoulder and due to the peculiarities of its mechanism I used 7-8 keys at the same time, then I solved the problem with the help of memory cells and forgot about this problem. I think you are right about the problem with the keyboard, although I do not know why it works like that. Now I bought an Xbox controller and there is no problem with the number of simultaneously pressed buttons
